### ISSUE TITLE
Nodeset compiler/GDS

### ISSUE THREAD

**Issue by opcua-tsn-team-kalycito** [open62541/open62541#2896]
## Description

For GDS implementation, while trying to build the datatypes and nodeset from _open62541/deps/ua-nodeset/GDS/_, Nodeset Compiler reports an error.

## Background Information / Reproduction Steps

While addressing one of the review [comments](https://github.com/open62541/open62541/pull/2299#discussion_r245254082), this issue was found:

Used CMake options:

```bash
cmake ../ -DUA_NAMESPACE_ZERO="FULL" -DUA_BUILD_EXAMPLES=TRUE
```
Added below modification to examples/nodeset/CMakeLists.txt
```bash
# Generate types and namespace for GDS
ua_generate_nodeset_and_datatypes(
    NAME "gds"
    FILE_CSV "${FILE_NS_DIRPREFIX}/GDS/OpcUaGdsModel.csv"
    FILE_BSD "${FILE_NS_DIRPREFIX}/GDS/Opc.Ua.Gds.Types.bsd"
    NAMESPACE_IDX 4
    FILE_NS "${FILE_NS_DIRPREFIX}/GDS/Opc.Ua.Gds.NodeSet2.xml"
    INTERNAL
)
```
The error log:
```bash
Scanning dependencies of target open62541-generator-types-gds
[ 88%] Generating ../../src_generated/open62541/types_gds_generated.c, ../../src_generated/open62541/types_gds_generated.h, ../../src_generated/open62541/types_gds_generated_handling.h, ../../src_generated/open62541/types_gds_generated_encoding_binary.h
Traceback (most recent call last):
  File "/home/jayanth/gds_ns_generate/open62541/tools/generate_datatypes.py", line 516, in <module>
    parseTypeDefinitions(outname, f, args.namespace)
  File "/home/jayanth/gds_ns_generate/open62541/tools/generate_datatypes.py", line 358, in parseTypeDefinitions
    raise RuntimeError("Infinite loop detected trying to processing types " + name + ": unknonwn subtype " + str(unknownTypes(typeXml)))
RuntimeError: Infinite loop detected trying to processing types ApplicationRecordDataType: unknonwn subtype ['ApplicationType']
examples/nodeset/CMakeFiles/open62541-generator-types-gds.dir/build.make:65: recipe for target 'src_generated/open62541/types_gds_generated.c' failed
make[2]: *** [src_generated/open62541/types_gds_generated.c] Error 1
CMakeFiles/Makefile2:1365: recipe for target 'examples/nodeset/CMakeFiles/open62541-generator-types-gds.dir/all' failed
make[1]: *** [examples/nodeset/CMakeFiles/open62541-generator-types-gds.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

While building with python script
```bash
$ python generate_datatypes.py --namespace=2 --type-csv=../deps/ua-nodeset/GDS/OpcUaGdsModel.csv --type-bsd=../deps/ua-nodeset/GDS/Opc.Ua.Gds.Types.bsd --no-builtin ua_types_gds
```
The error log 
```bash
Traceback (most recent call last):
  File "generate_datatypes.py", line 516, in <module>
    parseTypeDefinitions(outname, f, args.namespace)
  File "generate_datatypes.py", line 358, in parseTypeDefinitions
    raise RuntimeError("Infinite loop detected trying to processing types " + name + ": unknonwn subtype " + str(unknownTypes(typeXml)))
RuntimeError: Infinite loop detected trying to processing types ApplicationRecordDataType: unknonwn subtype ['ApplicationType']
```
## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): master
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Linux (Ubuntu 18.04)
 - [x] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by Pro** [comment]
Thanks for the issue report. This will be fixed with #2897 

An exemplary call for GDS is also listed in that PR.
