### ISSUE TITLE
gmake doc fails if LANG=C

### ISSUE THREAD

**Issue by jwith** [open62541/open62541#2928]
## Description

[  2%] Built target open62541-generator-transport
[  4%] Built target open62541-generator-types
[ 15%] Built target open62541-plugins
[ 15%] Built target open62541-generator-statuscode
[ 17%] Built target open62541-generator-namespace
[ 19%] Built target open62541-amalgamation-header
[ 71%] Built target open62541-object
[ 71%] Built target open62541
Scanning dependencies of target doc
[ 71%] Generating ../doc_src/tutorial_server_method.rst
[ 71%] Generating ../doc_src/types.rst
Traceback (most recent call last):
  File "/imphome/imppg/.install/impmake/open62541/current/tools/c2rst.py", line 73, in <module>
    c = f.readlines()
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 391: ordinal not in range(128)
gmake[3]: *** [doc/CMakeFiles/doc.dir/build.make:85: doc_src/types.rst] Error 1
gmake[2]: *** [CMakeFiles/Makefile2:529: doc/CMakeFiles/doc.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:536: doc/CMakeFiles/doc.dir/rule] Error 2
gmake: *** [Makefile:355: doc] Error 2

## Background Information / Reproduction Steps

Fails like above if 

LANG=C
LC_ALL=C
LC_COLLATE=C
LC_MONETARY=C
LC_NUMERIC=C
LC_TIME=C

Succeeds if

LANG=en_US.iso885915
LC_ALL=en_US.iso885915

Used CMake options:

-- The C compiler identification is GNU 7.4.1
-- The CXX compiler identification is GNU 7.4.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.5") 
-- Found Git: /usr/bin/git (found version "2.16.4") 
fatal: Not a git repository (or any of the parent directories): .git
-- CMAKE_BUILD_TYPE not given; setting to 'Debug'
-- Found Sphinx: /usr/bin/sphinx-build  
-- Could NOT find LATEX (missing: LATEX_COMPILER) 
-- Configuring done
-- Generating done
-- Build files have been written to: /imphome/imppg/.install/impmake/open62541/open62541-0.3.0
-- Cache values
BUILD_SHARED_LIBS:BOOL=OFF
CMAKE_BUILD_TYPE:STRING=Debug
CMAKE_INSTALL_PREFIX:PATH=/usr/local
LIB_INSTALL_DIR:PATH=lib
UA_BUILD_EXAMPLES:BOOL=OFF
UA_BUILD_UNIT_TESTS:BOOL=OFF
UA_ENABLE_AMALGAMATION:BOOL=OFF
UA_ENABLE_COVERAGE:BOOL=OFF
UA_ENABLE_DISCOVERY:BOOL=ON
UA_ENABLE_DISCOVERY_MULTICAST:BOOL=OFF
UA_ENABLE_ENCRYPTION:BOOL=OFF
UA_ENABLE_FULL_NS0:BOOL=OFF
UA_ENABLE_METHODCALLS:BOOL=ON
UA_ENABLE_NODEMANAGEMENT:BOOL=ON
UA_ENABLE_SUBSCRIPTIONS:BOOL=ON
UA_LOGLEVEL:STRING=300

```bash
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): 0.3.0
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: openSUSE 15
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by teccheck** [comment]
I've tested building the docs with `LANG=C`. It seems to be fixed now
