### ISSUE TITLE
Compiling MachineVision Nodeset

### ISSUE THREAD

**Issue by prrw** [open62541/open62541#2986]
I am compiling XML using Opc.Ua.MachineVision.NodeSet2 using the nodeset_compilor and it is showing error. It works with Opc.Ua.NodeSet2 but the XML is based on MachineVision.NodeSet2. 
`python ./nodeset_compiler.py --types-array=UA_TYPES --existing ./UA-Nodeset/MachineVision/Opc.Ua.MachineVision.NodeSet2.xml --xml 2DSensor.xml 2DSensor`
gives
```
Traceback (most recent call last):
  File "./nodeset_compiler.py", line 173, in <module>
    ns.sanitize()
  File "/usr/share/open62541/tools/nodeset_compiler/nodeset.py", line 136, in sanitize
    raise Exception("Reference " + str(ref) + " has an unknown reference type")
Exception: Reference ns=2;i=1023<--[ns=0;i=46]--ns=2;i=1022 has an unknown reference type
```
Did someone get it working ?

**Comment by teccheck** [comment]
This is now tested by the CI so it should be fixed
