### ISSUE TITLE
Segmentation fault within UA_Server_new(): PubSub and full namespace zero enabled

### ISSUE THREAD

**Issue by MartinaFelberFEM** [open62541/open62541#3121]
Hello!

I played around with the PubSub tutorials. I checked out the current master branch version today: 
commit hash: ```de8dd8191b42b75fe2c30b4b3e6313eb4c3b9e2d```

With following CMake options everything works fine: 
```bash cmake .. -DUA_ENABLE_PUBSUB=YES -DUA_ENABLE_PUBSUB_ETH_UADP=YES -DUA_ENABLE_PUBSUB_CUSTOM_PUBLISH_HANDLING=YES -DUA_ENABLE_MALLOC_SINGLETON=YES -DUA_ENABLE_IMMUTABLE_NODES=YES -DUA_ENABLE_PUBSUB_INFORMATIONMODEL=YES -DUA_ENABLE_PUBSUB_INFORMATIONMODEL_METHODS=YES ```

But if I want to use full namespace zero, a segmentation fault occurs at UA_Server_new();
```bash cmake .. -DUA_NAMESPACE_ZERO=FULL -DUA_ENABLE_PUBSUB=YES -DUA_ENABLE_PUBSUB_ETH_UADP=YES -DUA_ENABLE_PUBSUB_CUSTOM_PUBLISH_HANDLING=YES -DUA_ENABLE_MALLOC_SINGLETON=YES -DUA_ENABLE_IMMUTABLE_NODES=YES -DUA_ENABLE_PUBSUB_INFORMATIONMODEL=YES -DUA_ENABLE_PUBSUB_INFORMATIONMODEL_METHODS=YES ```

```UA_Server_new()``` is the first function I execute in my program. 

I am using Debian Linux: Debian GNU/Linux 8 (jessie)
GCC: gcc (Debian 4.9.2-10+deb8u2) 4.9.2

Shortened callstack: 

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xaf16b027 in cmpNodeId (a=0xaf6e787c, b=0xb2e96f50) at /home/admin/open62541/plugins/ua_nodestore_default.c:42
#1  0xaf16b32b in __NodeTree_ZIP_FIND (root=0xb2e96f50, key=0xaf6e787c) at /home/admin/open62541/plugins/ua_nodestore_default.c:67

....

#2512 0xaf16b36a in __NodeTree_ZIP_FIND (root=0xb2cdaaa0, key=0xaf6e787c) at /home/admin/open62541/plugins/ua_nodestore_default.c:67
#2513 0xaf16b36a in __NodeTree_ZIP_FIND (root=0xb2cd89d0, key=0xaf6e787c) at /home/admin/open62541/plugins/ua_nodestore_default.c:67
#2514 0xaf16b36a in __NodeTree_ZIP_FIND (root=0xb2cd8d10, key=0xaf6e787c) at /home/admin/open62541/plugins/ua_nodestore_default.c:67
#2515 0xaf16b36a in __NodeTree_ZIP_FIND (root=0xb2cde900, key=0xaf6e787c) at /home/admin/open62541/plugins/ua_nodestore_default.c:67
#2516 0xaf16b36a in __NodeTree_ZIP_FIND (root=0xb2cddd10, key=0xaf6e787c) at /home/admin/open62541/plugins/ua_nodestore_default.c:67
#2517 0xaf16b36a in __NodeTree_ZIP_FIND (root=0xb2cd88c0, key=0xaf6e787c) at /home/admin/open62541/plugins/ua_nodestore_default.c:67
2518 0xaf16b36a in __NodeTree_ZIP_FIND (root=0xb2cea8e0, key=0xaf6e787c) at /home/admin/open62541/plugins/ua_nodestore_default.c:67
#2519 0xaf16b386 in NodeTree_ZIP_FIND (head=0xb2cb1900, key=0xaf6e787c) at /home/admin/open62541/plugins/ua_nodestore_default.c:67
#2520 0xaf16b8b6 in UA_Nodestore_insertNode (nsCtx=0xb2cb1900, node=0xb2fb4b78, addedNodeId=0xaf6e7974) at /home/admin/open62541/plugins/ua_nodestore_default.c:218
#2521 0xaed76b6c in AddNode_raw (server=0xb2cb1530, session=0xb2cb171c, nodeContext=0x0, item=0xaf6e79e4, outNewNodeId=0xaf6e7974) at /home/admin/open62541/src/server/ua_services_nodemanagement.c:897
#2522 0xaed76db1 in Operation_addNode_begin (server=0xb2cb1530, session=0xb2cb171c, nodeContext=0x0, item=0xaf6e79e4, parentNodeId=0xaf6e7ad0, referenceTypeId=0xaf6e7ae8, outNewNodeId=0xaf6e7974) at /home/admin/open62541/src/server/ua_services_nodemanagement.c:926
#2523 0xaed78429 in UA_Server_addNode_begin (server=0xb2cb1530, nodeClass=UA_NODECLASS_OBJECT, requestedNewNodeId=..., parentNodeId=..., referenceTypeId=..., browseName=..., typeDefinition=..., attr=0xaf6e7c2c, attributeType=0xaf273558 <UA_TYPES+11480>, nodeContext=0x0, outNewNodeId=0x0) at /home/admin/open62541/src/server/ua_services_nodemanagement.c:1373
#2524 0xaef9006d in function_namespace0_generated_2584_begin (server=0xb2cb1530, ns=0xaf6e7c96) at /home/admin/open62541/build/src_generated/open62541/namespace0_generated.c:72997
#2525 0xaf143036 in namespace0_generated (server=0xb2cb1530) at /home/admin/open62541/build/src_generated/open62541/namespace0_generated.c:115719
#2526 0xaed5c4ea in UA_Server_initNS0 (server=0xb2cb1530) at /home/admin/open62541/src/server/ua_server_ns0.c:759
#2527 0xaed58a69 in UA_Server_init (server=0xb2cb1530) at /home/admin/open62541/src/server/ua_server.c:268
#2528 0xaed58ada in UA_Server_new () at /home/admin/open62541/src/server/ua_server.c:290
``` 

See full callstack: [Callstack.txt](https://github.com/open62541/open62541/files/3635125/Callstack.txt) 

I added a log at ```UA_Nodestore_insertNode()``` function to print the number of times the function has been called and the ```node->nodeId``` parameter. 

It seems that the segmentation fault occurs at NodeId = i=21175. It's the last log I get before the crash.

```
[2019-09-20 11:09:19.173 (UTC+0200)] info/server        UA_Nodestore_insertNode begin(): call # 2616
[2019-09-20 11:09:19.173 (UTC+0200)] info/server        UA_Nodestore_insertNode: NodeId = i=21175
``` 

This nodeId should be ```#define OpcUaId_NetworkAddressDataType_Encoding_DefaultXml 21175 ```

But I don't know whats wrong or how to fix it. 

Many thanks in advance for your support. 

Best regards
Martina

**Comment by MartinaFelberFEM** [comment]
I have pulled from the master branch today, there were some commits since last Friday and now the example is working with full namespace zero enabled. I don't know why it's working now, but the issue is resolved for me. 

Sry for the inconvenience I've caused.
