### ISSUE TITLE
openssl related ccmake flags and mbedtls ccmake flags - can these be turned on at the same time 

### ISSUE THREAD

**Issue by jackybek** [open62541/open62541#4402]
## Description
segmentation fault :

## Background Information / Reproduction Steps
Prior to v1.2.1, i only turn on the flags for openssl and set UA_NAMESPACE_ZERO = REDUCED.  Everything runs smoothly.
In v1.2.1, i decided to turn on the flags related to mbedtls and set UA_NAMESPACE_ZERO=FULL.

When i build and run my program, it crashed at 
UA_ServerConfig_setDefaultWithSecurityPolicies(&config1, 4840,             
                                                       &certificate, &privateKey,
                                                       trustList, trustListSize,
                                                       issuerList, issuerListSize,
                                                       revocationList, revocationListSize);

Question : Can openssl and mbedtls options co-exists at the same time?

Used CMake options:

```bash
cmake -DUA_NAMESPACE_ZERO=<YOUR_OPTION> <ANY_OTHER_OPTIONS> ..
```

## Checklist

Please provide the following information:

 - [X] open62541 Version (release number or git tag): v1.2.1
 - [ ] Other OPC UA SDKs used (client or server): 
 - [X] Operating system: raspbian
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [X] Critical issue

Core dump backtrace:
Program received signal SIGSEGV, Segmentation fault.
0xb6fb9bf0 in memcpy () from /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so
(gdb) backtrace
#0  0xb6fb9bf0 in memcpy () from /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so
#1  0x00000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)

**Comment by jackybek** [comment]
Issue is resolved : v1.2.2
