### ISSUE TITLE
Error using nodeset_compiler with v1.0 

### ISSUE THREAD

**Issue by acasanovaarg** [open62541/open62541#4451]
## Description
Hello,
I am starting to use open62541 with qtopcua 5.15.2. This uses open62541 v1.0. I was trying to put together an example with DI, Machinery, etc. but nodeset_compiler.py fails when trying to use Opc.Ua.Di.NodeSet2.xml

## Background Information / Reproduction Steps
I run it as follows: 
`python ./nodeset_compiler.py --internal-headers --types-array=UA_TYPES --types-array=UA_TYPES_DI --existing ../../deps/ua-nodeset/Schema/Opc.Ua.NodeSet2.xml --xml ../../deps/ua-nodeset/DI/Opc.Ua.Di.NodeSet2.xml namespace_di_generated`

o
```
# Generate types and namespace for DI
ua_generate_nodeset_and_datatypes(
  NAME "di"
  FILE_NS "${open62541_NODESET_DIR}/DI/Opc.Ua.Di.NodeSet2.xml"
  FILE_CSV "${open62541_NODESET_DIR}/DI/OpcUaDiModel.csv"
  FILE_BSD "${open62541_NODESET_DIR}/DI/Opc.Ua.Di.Types.bsd"
  NAMESPACE_IDX 2
  INTERNAL
)
```

and the error it indicates is: 
```
INFO:__main__:Preprocessing (existing) ../../deps/ua-nodeset/Schema/Opc.Ua.NodeSet2.xml
INFO:__main__:Preprocessing ../../deps/ua-nodeset/DI/Opc.Ua.Di.NodeSet2.xml
INFO:__main__:Generating Code for Backend: open62541
Traceback (most recent call last):
  File "D:\Proyectos\Otros\open62541\tools\nodeset_compiler\nodeset_compiler.py", line 202, in <module>
    generateOpen62541Code(ns, args.outputFile, args.internal_headers, args.typesArray)
  File "D:\Proyectos\Otros\open62541\tools\nodeset_compiler\backend_open62541.py", line 237, in generateOpen62541Code
    code = generateNodeCode_begin(node, nodeset, code_global)
  File "D:\Proyectos\Otros\open62541\tools\nodeset_compiler\backend_open62541_nodes.py", line 495, in generateNodeCode_begin
    [code1, codeCleanup1, codeGlobal1] = generateVariableNodeCode(node, nodeset)
  File "D:\Proyectos\Otros\open62541\tools\nodeset_compiler\backend_open62541_nodes.py", line 233, in generateVariableNodeCode
    [code1, codeCleanup1, codeGlobal1] = generateCommonVariableCode(node, nodeset)
  File "D:\Proyectos\Otros\open62541\tools\nodeset_compiler\backend_open62541_nodes.py", line 194, in generateCommonVariableCode
    [code1, codeCleanup1, codeGlobal1] = generateValueCode(node.value, nodeset.nodes[node.id], nodeset)
  File "D:\Proyectos\Otros\open62541\tools\nodeset_compiler\backend_open62541_nodes.py", line 434, in generateValueCode
    code.append(generateNodeValueCode("*" + valueName + " = " , node.value[0], instanceName, valueName, codeGlobal, asIndirect=True))
  File "D:\Proyectos\Otros\open62541\tools\nodeset_compiler\backend_open62541_datatypes.py", line 122, in generateNodeValueCode
    return prepend + generateQualifiedNameCode(node.value, alloc=asIndirect) + ";"
  File "D:\Proyectos\Otros\open62541\tools\nodeset_compiler\backend_open62541_datatypes.py", line 73, in generateQualifiedNameCode
    vn = makeCLiteral(value.name)
AttributeError: 'NoneType' object has no attribute 'name'
```

## Checklist

Please provide the following information:

 - [ ] open62541 Version (release number or git tag): v1.0.6
 - [ ] Other OPC UA SDKs used (client or server): 
 - [ ] Operating system: Win10
 - [ ] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by acasanovaarg** [comment]
Hello,
I've been debugging nodeset_compiler to detect where the error occurs.
When trying to use it with DI, IA, Machinery, and MachineTool, I encountered the following sources of error: 
  
backend_open62541_datatypes.py: line 122:
`generateQualifiedNameCode(node.value, alloc=asIndirect)`
Replace with : 
`generateQualifiedNameCode(node, alloc=asIndirect)` 

backend_open62541_nodes.py: line 262:
`logger.debug("Value    " + str(node.value))`
Comment that line 

By making these changes you can generate the necessary files

**Comment by andreasebner** [comment]
The DI nodeset is covered in our CI for a year now and should be working.
