### ISSUE TITLE
PubSub subscriber crashes when publisher and subscriber disagree about value datatype

### ISSUE THREAD

**Issue by JuhaSointusalo** [open62541/open62541#5639]
## Description

If publisher is sending data with one type but subscriber is expecting another type then the subscriber crashes when trying to handle that. For example, publisher sends DateTime but subscriber expects Int32.

```
[2023-02-14 18:06:20.081 (UTC+0200)] trace/eventloop    Iterate the EventLoop
[2023-02-14 18:06:20.082 (UTC+0200)] debug/pubsub       ReaderGroup ns=1;i=50448        | PubSub subscribe callback
[2023-02-14 18:06:20.082 (UTC+0200)] debug/pubsub       ReaderGroup ns=1;i=50448        | Reader ns=1;i=50450   | Process Msg with DataSetReader!
[2023-02-14 18:06:20.082 (UTC+0200)] debug/pubsub       ReaderGroup ns=1;i=50448        | Reader ns=1;i=50450   | DataSetReader 'DataSet Reader 1': received a network message
[2023-02-14 18:06:20.082 (UTC+0200)] trace/session      TCP 0   | SC 0  | Session "Administrator"       | Write attribute 13 of Node ns=1;i=50000
tutorial_pubsub_subscribe: /media/projects/open62541/arch/posix/ua_architecture.h:173: UA_LOCK_ASSERT: Assertion `lock->mutexCounter == num' failed.
```

I would have expected the subscriber to fail to process the incoming data and log an error message, not crash.

## Background Information / Reproduction Steps

Publisher is the `tutorial_pubsub_publish.c`. Subscriber is the `tutorial_pubsub_subscribe.c` with changed datatype for the first item:

```diff
diff --git a/examples/pubsub/tutorial_pubsub_subscribe.c b/examples/pubsub/tutorial_pubsub_subscribe.c
index 881de73..2590b64 100644
--- a/examples/pubsub/tutorial_pubsub_subscribe.c
+++ b/examples/pubsub/tutorial_pubsub_subscribe.c
@@ -235,9 +235,9 @@ static void fillTestDataSetMetaData(UA_DataSetMetaDataType *pMetaData) {

     /* DateTime DataType */
     UA_FieldMetaData_init (&pMetaData->fields[0]);
-    UA_NodeId_copy (&UA_TYPES[UA_TYPES_DATETIME].typeId,
+    UA_NodeId_copy (&UA_TYPES[UA_TYPES_INT32].typeId,
                     &pMetaData->fields[0].dataType);
-    pMetaData->fields[0].builtInType = UA_NS0ID_DATETIME;
+    pMetaData->fields[0].builtInType = UA_NS0ID_INT32;
     pMetaData->fields[0].name =  UA_STRING ("DateTime");
     pMetaData->fields[0].valueRank = -1; /* scalar */
```

Stack trace:

```
#0  0x00007ffff740bc37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff740f028 in __GI_abort () at abort.c:89
#2  0x00007ffff7404bf6 in __assert_fail_base (fmt=0x7ffff7559058 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x50b6b7 "lock->mutexCounter == num",
    file=file@entry=0x50b650 "/media/projects/open62541/arch/posix/ua_architecture.h", line=line@entry=173, function=function@entry=0x50bf69 <__PRETTY_FUNCTION__.5992> "UA_LOCK_ASSERT") at assert.c:92
#3  0x00007ffff7404ca2 in __GI___assert_fail (assertion=0x50b6b7 "lock->mutexCounter == num", file=0x50b650 "/media/projects/open62541/arch/posix/ua_architecture.h", line=173,
    function=0x50bf69 <__PRETTY_FUNCTION__.5992> "UA_LOCK_ASSERT") at assert.c:101
#4  0x0000000000437709 in UA_LOCK_ASSERT (lock=0x775ef8, num=1) at /media/projects/open62541/arch/posix/ua_architecture.h:173
#5  0x0000000000439f83 in readWithReadValue (server=0x7756c0, nodeId=0x767368 <UA_TYPES+872>, attributeId=UA_ATTRIBUTEID_ISABSTRACT, v=0x7fffffffd7fb) at /media/projects/open62541/src/server/ua_services_attribute.c:700
#6  0x000000000043a4da in compatibleValueDataType (server=0x7756c0, dataType=0x767360 <UA_TYPES+864>, constraintDataType=0x7cb018) at /media/projects/open62541/src/server/ua_services_attribute.c:836
#7  0x000000000043ad4b in compatibleValue (server=0x7756c0, session=0x775cd0, targetDataTypeId=0x7cb018, targetValueRank=-2, targetArrayDimensionsSize=0, targetArrayDimensions=0x0, value=0x7fffffffd930, range=0x0,
    reason=0x7fffffffd8e8) at /media/projects/open62541/src/server/ua_services_attribute.c:1073
#8  0x000000000043bcdd in writeNodeValueAttribute (server=0x7756c0, session=0x775cd0, node=0x7cafa0, value=0x7fffffffdb90, indexRange=0x7fffffffdb80) at /media/projects/open62541/src/server/ua_services_attribute.c:1433
#9  0x000000000043cd04 in copyAttributeIntoNode (server=0x7756c0, session=0x775cd0, node=0x7cafa0, wvalue=0x7fffffffdb60) at /media/projects/open62541/src/server/ua_services_attribute.c:1743
#10 0x00000000004164a1 in UA_Server_editNode (server=0x7756c0, session=0x775cd0, nodeId=0x7fffffffdb60, callback=0x43c5f4 <copyAttributeIntoNode>, data=0x7fffffffdb60) at /media/projects/open62541/src/server/ua_server_utils.c:280
#11 0x000000000043d3b1 in Operation_Write (server=0x7756c0, session=0x775cd0, context=0x0, wv=0x7fffffffdb60, result=0x7fffffffdb24) at /media/projects/open62541/src/server/ua_services_attribute.c:1823
#12 0x0000000000421bfb in UA_DataSetReader_process (server=0x7756c0, rg=0x7c7c40, dsr=0x7c5a70, msg=0x7cc030) at /media/projects/open62541/src/pubsub/ua_pubsub_reader.c:1267
#13 0x0000000000421eb8 in processMessageWithReader (server=0x7756c0, readerGroup=0x7c7c40, reader=0x7c5a70, msg=0x7fffffffddb0) at /media/projects/open62541/src/pubsub/ua_pubsub_reader.c:1373
#14 0x0000000000422014 in processNetworkMessage (server=0x7756c0, connection=0x7c06d0, msg=0x7fffffffddb0) at /media/projects/open62541/src/pubsub/ua_pubsub_reader.c:1405
#15 0x0000000000422565 in decodeAndProcessNetworkMessage (server=0x7756c0, connection=0x7c06d0, encodingMimeType=UA_PUBSUB_ENCODING_UADP, buf=0x7fffffffded0) at /media/projects/open62541/src/pubsub/ua_pubsub_reader.c:1561
#16 0x0000000000422975 in decodeAndProcessFun (channel=0x7c07f0, cbContext=0x7fffffffe070, buf=0x7fffffffdfa0) at /media/projects/open62541/src/pubsub/ua_pubsub_reader.c:1662
#17 0x00000000004d0b25 in UA_PubSubChannelUDPMC_receive (channel=0x7c07f0, transportSettings=0x7c7ca0, receiveCallback=0x4228ff <decodeAndProcessFun>, receiveCallbackContext=0x7fffffffe070, timeout=1000)
    at /media/projects/open62541/plugins/ua_pubsub_udp_multicast.c:773
#18 0x0000000000422ac3 in receiveBufferedNetworkMessage (server=0x7756c0, readerGroup=0x7c7c40, connection=0x7c06d0) at /media/projects/open62541/src/pubsub/ua_pubsub_reader.c:1701
#19 0x00000000004251a6 in UA_ReaderGroup_subscribeCallback (server=0x7756c0, readerGroup=0x7c7c40) at /media/projects/open62541/src/pubsub/ua_pubsub_readergroup.c:777
#20 0x00000000004df82e in processEntryCallback (context=0x7fffffffe1b0, te=0x7c7840) at /media/projects/open62541/arch/common/ua_timer.c:214
#21 0x000000000045054e in __ZIP_ITER (fieldoffset=0, cb=0x4df7ce <processEntryCallback>, context=0x7fffffffe1b0, elm=0x7c7840) at /media/projects/open62541/deps/ziptree.c:222
#22 0x00000000004df147 in UA_TimerTree_ZIP_ITER (head=0x774528, cb=0x4df7ce <processEntryCallback>, context=0x7fffffffe1b0) at /media/projects/open62541/arch/common/ua_timer.c:37
#23 0x00000000004df9f0 in UA_Timer_process (t=0x7744e0, nowMonotonic=8912816333079) at /media/projects/open62541/arch/common/ua_timer.c:269
#24 0x00000000004d1de6 in UA_EventLoopPOSIX_run (el=0x774440, timeout=200) at /media/projects/open62541/arch/eventloop_posix.c:248
#25 0x000000000040cc4b in UA_Server_run_iterate (server=0x7756c0, waitInternal=true) at /media/projects/open62541/src/server/ua_server.c:949
#26 0x00000000004ccd59 in UA_Server_runUntilInterrupt (server=0x7756c0) at /media/projects/open62541/plugins/ua_config_default.c:115
#27 0x0000000000402e29 in run (transportProfile=0x7fffffffe370, networkAddressUrl=0x7fffffffe380) at /media/projects/open62541/examples/pubsub/tutorial_pubsub_subscribe.c:309
#28 0x0000000000402fe9 in main (argc=1, argv=0x7fffffffe488) at /media/projects/open62541/examples/pubsub/tutorial_pubsub_subscribe.c:347
```

Used CMake options:

```bash
cmake -DUA_BUILD_EXAMPLES=on -DUA_ENABLE_PUBSUB=on -DUA_ENABLE_PUBSUB_INFORMATIONMODEL=on -DUA_LOGLEVEL=100 -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=off -DUA_FORCE_WERROR=off ..
```
(inb4 I'm using UA_FORCE_WERROR=off because old compiler.)

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): 1.3.4-816-g73a60b5-dirty
 - [ ] Other OPC UA SDKs used (client or server): 
 - [x] Operating system: Ubuntu 140.04
 - [x] Logs (with `UA_LOGLEVEL` set as low as necessary) attached
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by jpfr** [comment]
True. This not acceptable.

@andreasebner pulling you in on this one.
Don’t we have fuzzing for PubSub??

**Comment by jpfr** [comment]
The problem is related to use of multi-threading. PubSub on 1.3 is **not thread-safe**.
This was however added to the master branch and will be part of the next 1.4 release.
The change is too invasive for backporting to 1.3.

If you can use the master branch, I advise to do so.
Otherwise disable multi-threading in the SDK. And potentially use an application-level mutex to protect.

This PR adds a warning to the build system.
https://github.com/open62541/open62541/pull/5641
