### ISSUE TITLE
nodeset_compiler keeps crashing

### ISSUE THREAD

**Issue by HeinzBakedBean** [open62541/open62541#6263]
## Background Information / Reproduction Steps

nodeset_compiler from open62541/tools/nodeset/nodeset_compiler.py keeps crashing.
 
**Commandline:**
python nodeset_compiler/nodeset_compiler.py -x myNS.xml -v myNS.xml.c

**Error** Message:
INFO:__main__:Preprocessing myNS.xml
Traceback (most recent call last):
  File "/home/user/OPC_UA/nodeset_compiler/nodeset_compiler.py", line 187, in <module>
    ns.sanitize()
  File "/home/user/OPC_UA/nodeset_compiler/nodeset.py", line 134, in sanitize
    raise Exception("Reference " + str(ref) + " has an unknown reference type")
Exception: Reference ns=1;i=4001<--[ns=0;i=45]--ns=0;i=33 has an unknown reference type

**System**
Linux 10341PWS 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 GNU/Linux

**Distribution**
lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

**Python**
python --version
Python 3.9.2

**XML-File**
Directly from the Tutorial (after my own file didn't work):
https://www.open62541.org/doc/1.3/nodeset_compiler.html?highlight=nodeset_compiler

**Is there anything I can do?**

**BTW.: The Readme.md has a dead link**

> more nodeset_compiler/README.md
# open62541 nodeset Compiler

The nodeset compiler is a collection of Python scripts that can parse OPC UA XML Namespace definition files and transform them into a class representat

....

Usage documentation and How-Tos can be found on the webpage: <https://open62541.org/doc/current/nodeset_compiler.html>

Used CMake options:

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag):
 - OPC_UA open62541: v1.3.8-1388-g7837c1d62

 - [x] Operating system:
 -**System**
Linux 10341PWS 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 GNU/Linux

**Distribution**
lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

**Comment by V-Strassheim** [comment]
To avoid the exception NS0 should also be added with _--existing ../../deps/ua-nodeset/Schema/Opc.Ua.NodeSet2.xml_
This is mentioned in documentation https://www.open62541.org/doc/master/nodeset_compiler.html

A proper call would be:
`python ./nodeset_compiler.py --types-array=UA_TYPES --existing ../../deps/ua-nodeset/Schema/Opc.Ua.NodeSet2.xml --xml myNS.xml myNS`

Dead link is also already fixed.

I would suggest to close this issue.

**Comment by maslankam** [comment]
python3 nodeset_compiler.py \
--types-array=UA_TYPES \
-e Opc.Ua.Xml.NodeSet2.xml \
-e Opc.Ua.Di.NodeSet2.xml \
-x myNS2.xml \
-x myNS3.xml \
-x myNS4.xml \
-v -v -v -v \
myNS

I have similiar problem. Tried solution from this discussion but still getting this error: 
nodeset.py", line 119, in sanitize
    raise Exception("Reference " + str(ref) + " has an unknown reference type")
Exception: Reference ns=1;i=3042<--[ns=0;i=45]--ns=0;i=15 has an unknown reference type
