### ISSUE TITLE
Alarms and Conditions: Server Crash when monitoring Server Object

### ISSUE THREAD

**Issue by m-meingast** [open62541/open62541#6594]
## Description
I have built open62541 with UA_ENABLE_SUBSCRIPTIONS_ALARMS_CONDITIONS and UA_ENABLE_SUBSCRIPTIONS_EVENTS. Then I followed the tutorial on OPC UA Alarms and Conditions (https://www.open62541.org/doc/master/tutorial_server_alarms_conditions.html) and integrated it into a 4diac FORTE project (https://github.com/eclipse-4diac/4diac-forte) for testing. The interaction with the created Condition Object works and I can inspect the values in the Data Access View of UaExpert. However, when I add any of the OPC UA Objects, the Server Object, the ConditionSourceObject, or the Condition1 Object, to the Event View the OPC UA Server crashes. The final output of the application is "UA_LOCK_ASSERT: Assertion \`lock->mutexCounter == num' failed". Here is a screenshot of the EventView in UaExpert after the Server crashed:

![image](https://github.com/user-attachments/assets/708795ae-c0ac-40b1-8497-ebfdb6d23cef)

I found that this issue only occurs, when the `Condition1` Object is added to the `ConditionSourceObject` with the `UA_Server_createCondition` method. Then, the Server has the `HasCondition` reference on `OffNormalAlarmType`, which is the type of `Condition1`. I included the console output of the application as well as the call stack and backtrace of the debugger below.

I also followed the tutorial on OPC UA Events (https://www.open62541.org/doc/master/tutorial_server_events.html) where I did the same thing, i.e., testing it in the 4diac FORTE project and monitoring the generated Events with the Event View of UaExpert. There, everything worked fine and there were no issues at all. 

Am I missing something here or is my open62541 build configuration wrong?

- Console Output:
```
[2024-07-15 10:13:27.137 (UTC+0200)] warn/server        AccessControl: Unconfigured AccessControl. Users have all permissions.
[2024-07-15 10:13:27.137 (UTC+0200)] info/server        AccessControl: Anonymous login is enabled
[2024-07-15 10:13:27.137 (UTC+0200)] info/server        AccessControl: x509 certificate user authentication is enabled
[2024-07-15 10:13:27.137 (UTC+0200)] warn/server        Username/Password Authentication configured, but no encrypting SecurityPolicy. This can leak credentials on the network.
[2024-07-15 10:13:27.137 (UTC+0200)] warn/userland      AcceptAll Certificate Verification. Any remote certificate will be accepted.
INFO: T#1721031207147457113: [OPC UA LOGGER] info/network       TCP network layer listening on opc.tcp://XPS17:4840/
INFO: T#1721031208297679541: [OPC UA LOGGER] info/network       Connection 8 | New connection over TCP from ::1
INFO: T#1721031208348790420: [OPC UA LOGGER] info/channel       Connection 8 | SecureChannel 1 | SecureChannel opened with SecurityPolicy http://opcfoundation.org/UA/SecurityPolicy#None and a revised lifetime of 600.00s
WARNING: T#1721031208398278291: [OPC UA LOGGER] warning/channel Connection 8 | SecureChannel 1 | ActivateSession: Session not found
INFO: T#1721031208457313244: [OPC UA LOGGER] info/session       SecureChannel 1 | Session "urn:XPS17:UnifiedAutomation:UaExpert" | Session created
INFO: T#1721031208497879779: [OPC UA LOGGER] info/session       SecureChannel 1 | Session "urn:XPS17:UnifiedAutomation:UaExpert" | ActivateSession: Session activated
INFO: T#1721031208652080270: [OPC UA LOGGER] info/session       SecureChannel 1 | Session "urn:XPS17:UnifiedAutomation:UaExpert" | Subscription 1 | Subscription created (Publishing interval 100.00ms, max 1000 notifications per publish)
INFO: T#1721031208702232799: [OPC UA LOGGER] info/session       SecureChannel 1 | Session "urn:XPS17:UnifiedAutomation:UaExpert" | Subscription 1 | MonitoredItem 1 | Created the MonitoredItem (Sampling Interval: 50.00ms, Queue Size: 100)
INFO: T#1721031214402025416: [OPC UA LOGGER] info/session       SecureChannel 1 | Session "urn:XPS17:UnifiedAutomation:UaExpert" | Subscription 2 | Subscription created (Publishing interval 500.00ms, max 1000 notifications per publish)
INFO: T#1721031229057025664: [OPC UA LOGGER] info/session       SecureChannel 1 | Session "urn:XPS17:UnifiedAutomation:UaExpert" | Subscription 2 | MonitoredItem 1 | Created the MonitoredItem (Sampling Interval: 50.00ms, Queue Size: 100)
forte: /open62541/build/open62541.h:1120: UA_LOCK_ASSERT: Assertion `lock->mutexCounter == num' failed.
Aborted
```

- Call Stack:
```
libc.so.6!__pthread_kill_implementation(int no_tid, int signo, pthread_t threadid) (pthread_kill.c:44)
libc.so.6!__pthread_kill_internal(int signo, pthread_t threadid) (pthread_kill.c:78)
libc.so.6!__GI___pthread_kill(pthread_t threadid, int signo) (pthread_kill.c:89)
libc.so.6!__GI_raise(int sig) (raise.c:26)
libc.so.6!__GI_abort() (abort.c:79)
libc.so.6!__assert_fail_base(const char * fmt, const char * assertion, const char * file, unsigned int line, const char * function) (assert.c:92)
libc.so.6!__GI___assert_fail(const char * assertion, const char * file, unsigned int line, const char * function) (assert.c:101)
libopen62541.so.1!UA_LOCK_ASSERT(UA_Lock * lock, int num) (\open62541\build\open62541.h:1120)
libopen62541.so.1!UA_Server_getSessionById(UA_Server * server, const UA_NodeId * sessionId) (\open62541\build\open62541.c:44035)
libopen62541.so.1!refreshMethodCallback(UA_Server * server, const UA_NodeId * sessionId, void * sessionContext, const UA_NodeId * methodId, void * methodContext, const UA_NodeId * objectId, void * objectContext, size_t inputSize, const UA_Variant * input, size_t outputSize, UA_Variant * output) (\open62541\build\open62541.c:232022)
libopen62541.so.1!callWithMethodAndObject(UA_Server * server, UA_Session * session, const UA_CallMethodRequest * request, UA_CallMethodResult * result, const UA_MethodNode * method, const UA_ObjectNode * object) (\open62541\build\open62541.c:43726)
libopen62541.so.1!Operation_CallMethodAsync(UA_Server * server, UA_Session * session, UA_UInt32 requestId, UA_UInt32 requestHandle, size_t opIndex, UA_CallMethodRequest * opRequest, UA_CallMethodResult * opResult, UA_AsyncResponse ** ar) (\open62541\build\open62541.c:43759)
libopen62541.so.1!UA_Server_processServiceOperationsAsync(UA_Server * server, UA_Session * session, UA_UInt32 requestId, UA_UInt32 requestHandle, UA_AsyncServiceOperation operationCallback, const size_t * requestOperations, const UA_DataType * requestOperationsType, size_t * responseOperations, const UA_DataType * responseOperationsType, UA_AsyncResponse ** ar) (\open62541\build\open62541.c:33327)
libopen62541.so.1!Service_CallAsync(UA_Server * server, UA_Session * session, UA_UInt32 requestId, const UA_CallRequest * request, UA_CallResponse * response, UA_Boolean * finished) (\open62541\build\open62541.c:43800)
libopen62541.so.1!processMSGDecoded(UA_Server * server, UA_SecureChannel * channel, UA_UInt32 requestId, UA_Service service, const UA_Request * request, const UA_DataType * requestType, UA_Response * response, const UA_DataType * responseType, UA_Boolean sessionRequired, size_t counterOffset) (\open62541\build\open62541.c:32098)
libopen62541.so.1!processMSG(UA_Server * server, UA_SecureChannel * channel, UA_UInt32 requestId, const UA_ByteString * msg) (\open62541\build\open62541.c:32229)
libopen62541.so.1!processSecureChannelMessage(void * application, UA_SecureChannel * channel, UA_MessageType messagetype, UA_UInt32 requestId, UA_ByteString * message) (\open62541\build\open62541.c:32257)
libopen62541.so.1!assembleProcessMessage(UA_SecureChannel * channel, void * application, UA_ProcessMessageCallback * callback) (\open62541\build\open62541.c:26437)
libopen62541.so.1!processChunks(UA_SecureChannel * channel, void * application, UA_ProcessMessageCallback * callback) (\open62541\build\open62541.c:26584)
libopen62541.so.1!UA_SecureChannel_processBuffer(UA_SecureChannel * channel, void * application, UA_ProcessMessageCallback * callback, const UA_ByteString * buffer) (\open62541\build\open62541.c:26700)
libopen62541.so.1!UA_Server_processBinaryMessage(UA_Server * server, UA_Connection * connection, UA_ByteString * message) (\open62541\build\open62541.c:32327)
libopen62541.so.1!ServerNetworkLayerTCP_listen(UA_ServerNetworkLayer * nl, UA_Server * server, UA_UInt16 timeout) (\open62541\build\open62541.c:246768)
libopen62541.so.1!UA_Server_run_iterate(UA_Server * server, UA_Boolean waitInternal) (\open62541\build\open62541.c:29425)
COPC_UA_Local_Handler::run(COPC_UA_Local_Handler * const this) (\home\xps17\FORTE\4diac-forte\src\com\opc_ua\opcua_local_handler.cpp:101)
forte::arch::CThreadBase<unsigned long, 0ul, forte::arch::EmptyThreadDeletePolicy>::runThread(forte::arch::CThreadBase<unsigned long, 0, forte::arch::EmptyThreadDeletePolicy> * paThread) (\home\xps17\FORTE\4diac-forte\src\arch\threadbase.tpp:69)
CPosixThread::threadFunction(void * paArguments) (\home\xps17\FORTE\4diac-forte\src\arch\posix\forte_thread.cpp:68)
libc.so.6!start_thread(void * arg) (pthread_create.c:442)
libc.so.6!clone3() (clone3.S:81)const UA_ByteString * buffer) (\open62541\build\open62541.c:26700)
```

- Backtrace:
```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737129129536) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737129129536) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737129129536, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff6a70476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff6a567f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff6a5671b in __assert_fail_base (fmt=0x7ffff6c0b130 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7ffff74ca81b "lock->mutexCounter == num", file=0x7ffff74bd000 "/open62541/build/open62541.h", line=1120, function=<optimized out>) at ./assert/assert.c:92
#6  0x00007ffff6a67e96 in __GI___assert_fail (assertion=0x7ffff74ca81b "lock->mutexCounter == num", file=0x7ffff74bd000 "/open62541/build/open62541.h", line=1120, function=0x7ffff7549358 <__PRETTY_FUNCTION__.72> "UA_LOCK_ASSERT") at ./assert/assert.c:101
#7  0x00007ffff6fa9b81 in UA_LOCK_ASSERT (lock=0x61e000000a10, num=1) at /open62541/build/open62541.h:1120
#8  0x00007ffff6fd71e4 in UA_Server_getSessionById (server=0x61e000000080, sessionId=0x61900002fec0) at /open62541/build/open62541.c:44035
#9  0x00007ffff74ad171 in refreshMethodCallback (server=0x61e000000080, sessionId=0x61900002fec0, sessionContext=0x0, methodId=0x61100002a350, methodContext=0x0, objectId=0x61100003fed0, objectContext=0x0, inputSize=1, input=0x604000069dd0, outputSize=0, output=0x1) at /open62541/build/open62541.c:232022
#10 0x00007ffff6fd630f in callWithMethodAndObject (server=0x61e000000080, session=0x61900002fdf8, request=0x606000091580, result=0x6060000915e0, method=0x61100002a350, object=0x61100003fed0) at /open62541/build/open62541.c:43726
#11 0x00007ffff6fd6451 in Operation_CallMethodAsync (server=0x61e000000080, session=0x61900002fdf8, requestId=557, requestHandle=1000923, opIndex=0, opRequest=0x606000091580, opResult=0x6060000915e0, ar=0x7fffea969028) at /open62541/build/open62541.c:43759
#12 0x00007ffff6fd16aa in UA_Server_processServiceOperationsAsync (server=0x61e000000080, session=0x61900002fdf8, requestId=557, requestHandle=1000923, operationCallback=0x7ffff6fd6359 <Operation_CallMethodAsync>, requestOperations=0x7fffea969740, requestOperationsType=0x555556751310 <UA_TYPES+20592>, responseOperations=0x7fffea969628, responseOperationsType=0x555556751358 <UA_TYPES+20664>, ar=0x7fffea969028) at /open62541/build/open62541.c:33327
#13 0x00007ffff6fd6697 in Service_CallAsync (server=0x61e000000080, session=0x61900002fdf8, requestId=557, request=0x7fffea9696d0, response=0x7fffea9695a0, finished=0x7fffea9690cb) at /open62541/build/open62541.c:43800
#14 0x00007ffff6fce397 in processMSGDecoded (server=0x61e000000080, channel=0x6140000216b8, requestId=557, service=0x7ffff6fd6919 <Service_Call>, request=0x7fffea9696d0, requestType=0x5555567513a0 <UA_TYPES+20736>, response=0x7fffea9695a0, responseType=0x5555567513e8 <UA_TYPES+20808>, sessionRequired=true, counterOffset=296) at /open62541/build/open62541.c:32098
#15 0x00007ffff6fcea8d in processMSG (server=0x61e000000080, channel=0x6140000216b8, requestId=557, msg=0x604000069d98) at /open62541/build/open62541.c:32229
#16 0x00007ffff6fcecb1 in processSecureChannelMessage (application=0x61e000000080, channel=0x6140000216b8, messagetype=UA_MESSAGETYPE_MSG, requestId=557, message=0x604000069d98) at /open62541/build/open62541.c:32257
#17 0x00007ffff6fbe8b2 in assembleProcessMessage (channel=0x6140000216b8, application=0x61e000000080, callback=0x7ffff6fceae5 <processSecureChannelMessage>) at /open62541/build/open62541.c:26437
#18 0x00007ffff6fbef96 in processChunks (channel=0x6140000216b8, application=0x61e000000080, callback=0x7ffff6fceae5 <processSecureChannelMessage>) at /open62541/build/open62541.c:26584
#19 0x00007ffff6fbf41b in UA_SecureChannel_processBuffer (channel=0x6140000216b8, application=0x61e000000080, callback=0x7ffff6fceae5 <processSecureChannelMessage>, buffer=0x7fffea969a90) at /open62541/build/open62541.c:26700
#20 0x00007ffff6fcf012 in UA_Server_processBinaryMessage (server=0x61e000000080, connection=0x60b00001cfa0, message=0x7fffea969a90) at /open62541/build/open62541.c:32327
#21 0x00007ffff74bb2bc in ServerNetworkLayerTCP_listen (nl=0x6080000a3c20, server=0x61e000000080, timeout=0) at /open62541/build/open62541.c:246768
#22 0x00007ffff6fc5c23 in UA_Server_run_iterate (server=0x61e000000080, waitInternal=false) at /open62541/build/open62541.c:29425
#23 0x00005555562efec6 in COPC_UA_Local_Handler::run (this=0x616000000380) at /home/xps17/FORTE/4diac-forte/src/com/opc_ua/opcua_local_handler.cpp:101
#24 0x0000555555d7e0b0 in forte::arch::CThreadBase<unsigned long, 0ul, forte::arch::EmptyThreadDeletePolicy>::runThread (paThread=0x616000000390) at /home/xps17/FORTE/4diac-forte/src/arch/posix/../threadbase.tpp:69
#25 0x0000555555d7d9b8 in CPosixThread::threadFunction (paArguments=0x616000000390) at /home/xps17/FORTE/4diac-forte/src/arch/posix/forte_thread.cpp:68
#26 0x00007ffff6ac2ac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#27 0x00007ffff6b54850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

```

## Background Information / Reproduction Steps

Used CMake options:

```
BUILD_SHARED_LIBS:BOOL=ON
CMAKE_BUILD_TYPE:STRING=Debug
CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/g++
CMAKE_C_COMPILER:FILEPATH=/usr/bin/gcc
CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE
Python3_EXECUTABLE:FILEPATH=/usr/bin/python3
UA_ARCHITECTURE:STRING=posix
UA_DEBUG:BOOL=ON
UA_ENABLE_AMALGAMATION:BOOL=ON
UA_ENABLE_DA:BOOL=ON
UA_ENABLE_DATATYPES_ALL:BOOL=ON
UA_ENABLE_DEBUG_SANITIZER:BOOL=ON
UA_ENABLE_DIAGNOSTICS:BOOL=ON
UA_ENABLE_DISCOVERY:BOOL=ON
UA_ENABLE_HISTORIZING:BOOL=ON
UA_ENABLE_JSON_ENCODING:BOOL=ON
UA_ENABLE_METHODCALLS:BOOL=ON
UA_ENABLE_SUBSCRIPTIONS:BOOL=ON
UA_ENABLE_SUBSCRIPTIONS_ALARMS_CONDITIONS:BOOL=ON
UA_ENABLE_SUBSCRIPTIONS_EVENTS:BOOL=ON
UA_LOGLEVEL:STRING=100
UA_MULTITHREADING:STRING=100
UA_NAMESPACE_ZERO:STRING=FULL
```

## Checklist

Please provide the following information:

 - [x] open62541 Version (release number or git tag): v1.3.11
 - [x] Other OPC UA SDKs used (client or server): UaExpert v1.7.1
 - [x] Operating system: Ubuntu 22.04.3 LTS on Microsoft WSL2
 - [x] Logs (with `UA_LOGLEVEL` set as low as necessary) attached: Loglevel 100
 - [ ] Wireshark network dump attached
 - [ ] Self-contained code example attached
 - [ ] Critical issue

**Comment by m-meingast** [comment]
Thank you for the information. We have to do some rework in order to upgrade to 1.4., but we will try and test that.

**Comment by m-meingast** [comment]
We finally switched to the 1.4 release and the problem disappeared. OPC UA Alarms can now be monitored in UAExpert without any workaround. Thank you again!
