### ISSUE TITLE
ubuntu 16.04 x64 + gcc8

### ISSUE THREAD

**Issue by QingruiHuang** [open62541/open62541#6675]
Traceback (most recent call last):
  File "/mnt/e/GitHub/open62541/tools/generate_datatypes.py", line 7, in <module>
    from nodeset_compiler.type_parser import CSVBSDTypeParser
  File "/mnt/e/GitHub/open62541/tools/nodeset_compiler/type_parser.py", line 108
    f"Exception: {ex}")
                     ^
SyntaxError: invalid syntax
CMakeFiles/open62541-generator-transport.dir/build.make:77: recipe for target 'src_generated/open62541/transport_generated.c' failed
make[2]: *** [src_generated/open62541/transport_generated.c] Error 1
CMakeFiles/Makefile2:217: recipe for target 'CMakeFiles/open62541-generator-transport.dir/all' failed
make[1]: *** [CMakeFiles/open62541-generator-transport.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by teccheck** [comment]
This seems to be a problem with the python version you're using. As you can read in the [docs](https://docs.python.org/3/reference/lexical_analysis.html#f-strings), f-strings were introduced in python 3.6. So you need to have at least that version installed.
