### ISSUE TITLE
[BUG] UA_NAMESPACE_ZERO=FULL compilation is broken

### ISSUE THREAD

**Issue by electro-logic** [open62541/open62541#6896]
Related to https://github.com/open62541/open62541-nodeset-loader/issues/266

I tried again to compile branch 1.4 on another machine, but I get a similar error:

`Exception: Reference ns=1;i=15235--[ns=0;i=40]-->ns=0;i=18791 has an unknown target`

below the full log

```
-- open62541 Version: v1.4.7-7-g7494e33
-- The selected architecture is: posix
-- Test CC flag -fstack-clash-protection
-- Performing Test flag_supported
-- Performing Test flag_supported - Failed
-- Test CC flag -mcet
-- Performing Test flag_supported
-- Performing Test flag_supported - Failed
-- Test CC flag -fcf-protection
-- Performing Test flag_supported
-- Performing Test flag_supported - Failed
CMake Deprecation Warning at deps/nodesetLoader/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


open62541 v1.4.7-7-g7494e33 is compatible to use the nodesetLoader.
-- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE)
-- Could NOT find LATEX (missing: LATEX_COMPILER)
-- Configuring done (14.1s)
-- Generating done (1.7s)
-- Build files have been written to: /home/ubuntu/open62541/build
[  0%] Generating src_generated/open62541/types_generated.c, src_generated/open62541/types_generated.h, src_generated/open    62541/types_generated_handling.h
[  0%] Generating src_generated/open62541/transport_generated.c, src_generated/open62541/transport_generated.h, src_genera    ted/open62541/transport_generated_handling.h
[  0%] Built target open62541-generator-transport
[  0%] Generating src_generated/open62541/nodeids.h
[  0%] Built target open62541-generator-types
[  1%] Generating src_generated/open62541/statuscodes.h, src_generated/open62541/statuscodes.c
[  1%] Built target open62541-generator-ids_example
[  1%] Built target open62541-generator-ns-example
[  2%] Generating ../../src_generated/open62541/testnodeset_nodeids.h
[  2%] Built target open62541-generator-ids-testnodeset
[  3%] Generating ../../src_generated/open62541/types_testnodeset_generated.c, ../../src_generated/open62541/types_testnod    eset_generated.h, ../../src_generated/open62541/types_testnodeset_generated_handling.h
[  3%] Built target open62541-generator-statuscode
[  5%] Generating ../../src_generated/open62541/di_nodeids.h
[  5%] Built target open62541-generator-types-testnodeset
[  6%] Generating ../../src_generated/open62541/types_di_generated.c, ../../src_generated/open62541/types_di_generated.h,     ../../src_generated/open62541/types_di_generated_handling.h
[  6%] Built target open62541-generator-ids-di
[  6%] Generating ../../src_generated/open62541/powerlink_nodeids.h
[  6%] Built target open62541-generator-ids-powerlink
[  6%] Generating ../../src_generated/open62541/types_powerlink_generated.c, ../../src_generated/open62541/types_powerlink    _generated.h, ../../src_generated/open62541/types_powerlink_generated_handling.h
[  6%] Built target open62541-generator-types-di
[  6%] Generating src_generated/open62541/namespace0_generated.c, src_generated/open62541/namespace0_generated.h
INFO:__main__:Preprocessing /home/ubuntu/open62541/tools/schema/Opc.Ua.NodeSet2.Reduced.xml
INFO:__main__:Generating Code for Backend: open62541
INFO:__main__:NodeSet generation code successfully printed
[  6%] Built target open62541-generator-namespace
[  6%] Generating ../../src_generated/open62541/namespace_testnodeset_generated.c, ../../src_generated/open62541/namespace    _testnodeset_generated.h
INFO:__main__:Preprocessing (existing) /home/ubuntu/open62541/tools/schema/Opc.Ua.NodeSet2.Reduced.xml
INFO:__main__:Preprocessing /home/ubuntu/open62541/examples/nodeset/testnodeset.xml
['http://opcfoundation.org/UA/', 'http://yourorganisation.org/test/']
Traceback (most recent call last):
  File "/home/ubuntu/open62541/tools/nodeset_compiler/nodeset_compiler.py", line 187, in <module>
    ns.sanitize()
  File "/home/ubuntu/open62541/tools/nodeset_compiler/nodeset.py", line 137, in sanitize
    raise Exception("Reference " + str(ref) + " has an unknown target")
Exception: Reference ns=1;i=15235--[ns=0;i=40]-->ns=0;i=18791 has an unknown target
examples/nodeset/CMakeFiles/open62541-generator-ns-testnodeset.dir/build.make:82: recipe for target 'src_generated/open625    41/namespace_testnodeset_generated.c' failed
make[2]: *** [src_generated/open62541/namespace_testnodeset_generated.c] Error 1
CMakeFiles/Makefile2:1631: recipe for target 'examples/nodeset/CMakeFiles/open62541-generator-ns-testnodeset.dir/all' fail    ed
make[1]: *** [examples/nodeset/CMakeFiles/open62541-generator-ns-testnodeset.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  6%] Built target open62541-generator-types-powerlink
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by electro-logic** [comment]
latest commit seems to have fixed this
