### ISSUE TITLE
Stress testing the server causes crash

### ISSUE THREAD

**Issue by StalderT** [open62541/open62541#800]
Hello,

I have add to server.c :
```
static UA_StatusCode
readTest(void *handle, const UA_NodeId nodeId, UA_Boolean sourceTimeStamp,
             const UA_NumericRange *range, UA_DataValue *value) {
    if(range) {
        value->hasStatus = UA_TRUE;
        value->status = UA_STATUSCODE_BADINDEXRANGEINVALID;
        return UA_STATUSCODE_GOOD;
    }   
    UA_UInt32 val = (UA_UInt32)handle;
    UA_DateTime currentTime = UA_DateTime_now();
    UA_Variant_setScalarCopy(&value->value, &val, &UA_TYPES[UA_TYPES_UINT32]);
    value->hasValue = UA_TRUE;
    if(sourceTimeStamp) {
        value->hasSourceTimestamp = UA_TRUE;
        value->sourceTimestamp = currentTime;
    }   
    return UA_STATUSCODE_GOOD;
}
```
and
```
    for(UA_UInt32 i=0; i<10000; i++)
    {
            UA_DataSource dateDataSource_test = (UA_DataSource) {.handle = (void*)i, .read = readTest, .write = NULL};
            UA_VariableAttributes v_attr_test;
            UA_VariableAttributes_init(&v_attr_test);
            char name[100];
            snprintf(name, 100, "TEST%04d", i);
            v_attr_test.description = UA_LOCALIZEDTEXT("en_US",name);
            v_attr_test.displayName = UA_LOCALIZEDTEXT("en_US",name);
            const UA_QualifiedName dateName_test = UA_QUALIFIEDNAME(1, name);
            UA_NodeId dataSourceId_test;
            UA_Server_addDataSourceVariableNode(server, UA_NODEID_NULL,
                                                UA_NODEID_NUMERIC(0, UA_NS0ID_OBJECTSFOLDER),
                                                UA_NODEID_NUMERIC(0, UA_NS0ID_ORGANIZES), dateName_test,
                                                UA_NODEID_NULL, v_attr_test, dateDataSource_test, &dataSourceId_test);
    }
```

If I add 4000 test variables to Data Access View in UaExpert, open62541 server crash : 

```
==11316== Memcheck, a memory error detector
==11316== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==11316== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==11316== Command: a.out
==11316== 
[09/19/2016 13:22:36.040] info/network	TCP network layer listening on opc.tcp://devel:16664
[09/19/2016 13:23:27.828] info/network	Connection 4 | New connection over TCP from 192.168.1.38:11561
[09/19/2016 13:23:27.891] info/channel	Connection 4 | SecureChannel 1 | OpenSecureChannel: Opened SecureChannel
[09/19/2016 13:23:27.923] info/channel	Connection 4 | SecureChannel 1 | CloseSecureChannel
[09/19/2016 13:23:27.928] info/network	Connection 4 | Connection closed from remote
[09/19/2016 13:23:30.733] info/network	Connection 4 | New connection over TCP from 192.168.1.38:11592
[09/19/2016 13:23:30.744] info/channel	Connection 4 | SecureChannel 2 | OpenSecureChannel: Opened SecureChannel
[09/19/2016 13:23:30.777] info/channel	Connection 4 | SecureChannel 2 | CloseSecureChannel
[09/19/2016 13:23:30.779] info/network	Connection 4 | Connection closed from remote
[09/19/2016 13:23:36.173] info/network	Connection 4 | New connection over TCP from 192.168.1.38:11617
[09/19/2016 13:23:36.178] info/channel	Connection 4 | SecureChannel 3 | OpenSecureChannel: Opened SecureChannel
[09/19/2016 13:23:36.185] info/channel	Connection 4 | SecureChannel 3 | CloseSecureChannel
[09/19/2016 13:23:36.187] info/network	Connection 4 | Connection closed from remote
[09/19/2016 13:23:36.193] info/network	Connection 4 | New connection over TCP from 192.168.1.38:11618
[09/19/2016 13:23:36.197] info/channel	Connection 4 | SecureChannel 4 | OpenSecureChannel: Opened SecureChannel
[09/19/2016 13:23:36.238] info/session	Connection 4 | SecureChannel 4 | Session {1CD777E3-9590-A4E2-6DB6-4BE40EE09EB9} | ActivateSession: Session activated
==11316== Invalid write of size 1
==11316==    at 0x402EE83: memcpy (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==11316==    by 0x404DE85: UA_Connection_completeMessages (open62541.c:14492)
==11316==    by 0x40584CC: completeMessages (open62541.c:17947)
==11316==    by 0x4058688: UA_Server_run_iterate (open62541.c:18004)
==11316==    by 0x405882C: UA_Server_run (open62541.c:18067)
==11316==    by 0x804BC17: main (in /data/a.out)
==11316==  Address 0xb84eb48 is 0 bytes after a block of size 88 alloc'd
==11316==    at 0x402A11C: malloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==11316==    by 0x40694F1: ServerNetworkLayerTCP_add (open62541.c:25537)
==11316==    by 0x4069AB8: ServerNetworkLayerTCP_getJobs (open62541.c:25664)
==11316==    by 0x4058634: UA_Server_run_iterate (open62541.c:17989)
==11316==    by 0x405882C: UA_Server_run (open62541.c:18067)
==11316==    by 0x804BC17: main (in /data/a.out)
==11316== 
[09/19/2016 13:23:44.569] info/network	Connection 4 | Received MSG with the channel id 4 not bound to the connection
==11316== Invalid read of size 4
==11316==    at 0x405A927: Service_CloseSecureChannel (open62541.c:19274)
==11316==    by 0x4057140: processMSG (open62541.c:17018)
==11316==    by 0x405758F: UA_Server_processBinaryMessage (open62541.c:17144)
==11316==    by 0x4057EFF: processJob (open62541.c:17502)
==11316==    by 0x40586B7: UA_Server_run_iterate (open62541.c:18012)
==11316==    by 0x405882C: UA_Server_run (open62541.c:18067)
==11316==    by 0x804BC17: main (in /data/a.out)
==11316==  Address 0x45 is not stack'd, malloc'd or (recently) free'd
==11316== 
==11316== 
==11316== Process terminating with default action of signal 11 (SIGSEGV)
==11316==  Access not within mapped region at address 0x45
==11316==    at 0x405A927: Service_CloseSecureChannel (open62541.c:19274)
==11316==    by 0x4057140: processMSG (open62541.c:17018)
==11316==    by 0x405758F: UA_Server_processBinaryMessage (open62541.c:17144)
==11316==    by 0x4057EFF: processJob (open62541.c:17502)
==11316==    by 0x40586B7: UA_Server_run_iterate (open62541.c:18012)
==11316==    by 0x405882C: UA_Server_run (open62541.c:18067)
==11316==    by 0x804BC17: main (in /data/a.out)
==11316==  If you believe this happened as a result of a stack
==11316==  overflow in your program's main thread (unlikely but
==11316==  possible), you can try to increase the size of the
==11316==  main thread stack using the --main-stacksize= flag.
==11316==  The main thread stack size used in this run was 8388608.
==11316== 
==11316== HEAP SUMMARY:
==11316==     in use at exit: 5,947,011 bytes in 71,611 blocks
==11316==   total heap usage: 184,025 allocs, 112,414 frees, 6,759,115,484 bytes allocated
==11316== 
==11316== LEAK SUMMARY:
==11316==    definitely lost: 1,318 bytes in 5 blocks
==11316==    indirectly lost: 0 bytes in 0 blocks
==11316==      possibly lost: 0 bytes in 0 blocks
==11316==    still reachable: 5,945,693 bytes in 71,606 blocks
==11316==         suppressed: 0 bytes in 0 blocks
==11316== Rerun with --leak-check=full to see details of leaked memory
==11316== 
==11316== For counts of detected and suppressed errors, rerun with: -v
==11316== ERROR SUMMARY: 1038 errors from 2 contexts (suppressed: 0 from 0)
Segmentation fault

```

I use the latest 0.2 git version

Thanks for your help.

**Comment by StalderT** [comment]
Hello,

I have memory erros with your sample code on linux (32 bits gcc version 5.3.0 (GCC) ): 

```
[root@devel data]$ valgrind ./a.out 
==959== Memcheck, a memory error detector
==959== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==959== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==959== Command: ./a.out
==959== 
[09/20/2016 08:23:59.220] info/network	TCP network layer listening on opc.tcp://devel:16664
[09/20/2016 08:23:59.683] info/network	Connection 4 | New connection over TCP from 192.168.1.38:32542
[09/20/2016 08:23:59.747] info/channel	Connection 4 | SecureChannel 1 | OpenSecureChannel: Opened SecureChannel
[09/20/2016 08:23:59.825] info/session	Connection 4 | SecureChannel 1 | Session {1CD777E3-9590-A4E2-6DB6-4BE40EE09EB9} | ActivateSession: Session activated
==959== Invalid write of size 1
==959==    at 0x402EE83: memcpy (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==959==    by 0x404DE85: UA_Connection_completeMessages (open62541.c:14492)
==959==    by 0x40584CC: completeMessages (open62541.c:17947)
==959==    by 0x4058688: UA_Server_run_iterate (open62541.c:18004)
==959==    by 0x405882C: UA_Server_run (open62541.c:18067)
==959==    by 0x8048D8D: main (in /data/a.out)
==959==  Address 0x550bb38 is 0 bytes after a block of size 88 alloc'd
==959==    at 0x402A11C: malloc (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==959==    by 0x40694F1: ServerNetworkLayerTCP_add (open62541.c:25537)
==959==    by 0x4069AB8: ServerNetworkLayerTCP_getJobs (open62541.c:25664)
==959==    by 0x4058634: UA_Server_run_iterate (open62541.c:17989)
==959==    by 0x405882C: UA_Server_run (open62541.c:18067)
==959==    by 0x8048D8D: main (in /data/a.out)
==959== 
```
```
(gdb) r
Starting program: /data/a.out 
[09/20/2016 08:43:52.951] info/network	TCP network layer listening on opc.tcp://devel:16664
[09/20/2016 08:43:54.119] info/network	Connection 4 | New connection over TCP from 192.168.1.38:32738
[09/20/2016 08:43:54.123] info/channel	Connection 4 | SecureChannel 1 | OpenSecureChannel: Opened SecureChannel
[09/20/2016 08:43:54.133] info/session	Connection 4 | SecureChannel 1 | Session {1CD777E3-9590-A4E2-6DB6-4BE40EE09EB9} | ActivateSession: Session activated

Program received signal SIGSEGV, Segmentation fault.
0xb7ec328e in realloc () from /lib/libc.so.6
(gdb) where
#0  0xb7ec328e in realloc () from /lib/libc.so.6
#1  0x0804f7ce in UA_Connection_completeMessages ()
#2  0x08059800 in completeMessages ()
#3  0x080599a9 in UA_Server_run_iterate ()
#4  0x08059b2f in UA_Server_run ()
#5  0x0804914e in main ()
```
The error occured when I add 4000 tests variables to Data Access View in UaExpert

I compile open62541 with  : 
```
cmake ../${pkgbase}-0.2 \
        -DCMAKE_BUILD_TYPE=Debug \
        -DUA_ENABLE_AMALGAMATION=ON \
        -DUA_ENABLE_SUBSCRIPTIONS=ON \
        -DUA_ENABLE_METHODCALLS=ON \
        -DUA_BUILD_EXAMPLESERVER=OFF \
        -DUA_BUILD_EXAMPLECLIENT=OFF \
        -DUA_LOGLEVEL=300 \
        -DBUILD_SHARED_LIBS=ON \
        -DUA_ENABLE_NODEMANAGEMENT=OFF
```
